'use client';
import { useState, type FormEvent } from 'react';
import Link from 'next/link';
import { Dialog, DialogContent, DialogTitle, DialogDescription, DialogTrigger, DialogClose } from '@/components/ui/dialog';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { siteConfig } from '@/lib/site-config';
import { services } from '@/lib/content';
export function ContactModal({label='DOMLUVIT SCHŮZKU',className='text-link'}:{label?:string;className?:string}){
 const [topic,setTopic]=useState('Úvodní schůzka');const [status,setStatus]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [draft,setDraft]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');setStatus('');setDraft('');const form=e.currentTarget;const data=new FormData(form);const name=String(data.get('name')||'').trim();const contact=String(data.get('contact')||'').trim();const message=String(data.get('message')||'').trim();
 if(name.length<2){setError('Napište prosím své jméno.');form.querySelector<HTMLInputElement>('[name=name]')?.focus();return}
 if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(contact)&&!/^\+?\d{9,15}$/.test(contact.replace(/[\s()-]/g,''))){setError('Zadejte platný e-mail nebo telefonní číslo.');form.querySelector<HTMLInputElement>('[name=contact]')?.focus();return}
 if(!siteConfig.contactEndpoint){setDraft(`mailto:${siteConfig.email}?subject=${encodeURIComponent(topic+' — '+name)}&body=${encodeURIComponent('Jméno: '+name+'\nKontakt: '+contact+'\nZájem: '+topic+'\n\n'+message)}`);setStatus('Zpráva je připravená. Otevřete ji v e-mailové aplikaci a odešlete. Z tohoto webu zatím nebyla odeslána.');return}
 // Integration contract: same-origin POST JSON; require { ok: true } from a real delivery service.
 setBusy(true);try{const response=await fetch(siteConfig.contactEndpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,contact,topic,message})});const result=await response.json();if(!response.ok||typeof result!=='object'||result===null||!('ok' in result)||result.ok!==true)throw new Error('delivery');setStatus('Děkuji, zpráva byla odeslána. Ozvu se vám.');form.reset()}catch{setError('Zprávu se nepodařilo odeslat. Zkuste to znovu nebo mi napište přímo e-mailem.')}finally{setBusy(false)} }
 return <Dialog><DialogTrigger className={className}>{label} <span>↗</span></DialogTrigger><DialogContent className="contact-modal" showCloseButton={false}><DialogClose className="close-link modal-close">ZAVŘÍT <span>×</span></DialogClose><p className="eyebrow">PRVNÍ KROK JE JEDNODUCHÝ</p><DialogTitle className="form-title">POJĎME TO<br/><em>PROBRAT.</em></DialogTitle><DialogDescription className="form-description">Napište mi pár slov. Společně najdeme vhodný čas.</DialogDescription><form onSubmit={submit} onChange={()=>{setDraft('');setStatus('');setError('')}}><div className="form-two"><label>JMÉNO A PŘÍJMENÍ<input name="name" autoComplete="name" required minLength={2} maxLength={100} placeholder="Jak se jmenujete?"/></label><label>TELEFON / E-MAIL<input name="contact" autoComplete="email" required maxLength={150} placeholder="Kde vás zastihnu?" aria-describedby={error?'form-error':undefined}/></label></div><label htmlFor="topic">O CO MÁTE ZÁJEM?</label><Select value={topic} onValueChange={v=>{setTopic(v);setDraft('');setStatus('')}}><SelectTrigger id="topic" className="topic-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="Úvodní schůzka">Úvodní schůzka</SelectItem>{services.map(s=><SelectItem key={s.id} value={s.title}>{s.title}</SelectItem>)}<SelectItem value="Něco jiného">Něco jiného</SelectItem></SelectContent></Select><label>ZPRÁVA <span className="optional">(NEPOVINNÉ)</span><textarea name="message" maxLength={2000} rows={3} placeholder="Co byste chtěli probrat?"/></label><p className="form-help">{siteConfig.contactEndpoint?'Odesláním poptávky předáváte své kontaktní údaje za účelem odpovědi.':'Formulář připraví zprávu do vaší e-mailové aplikace. Odešlete ji až v ní.'} <Link href="/dokumenty/osobni-udaje">Ochrana osobních údajů ↗</Link></p>{error&&<p className="form-error" role="alert" id="form-error">{error}</p>}{status&&<p className="form-status" role="status">{status}</p>}{draft?<a className="submit-button" href={draft}>OTEVŘÍT E-MAIL K ODESLÁNÍ <span>↗</span></a>:<button className="submit-button" disabled={busy} type="submit">{busy?'ODESÍLÁM…':siteConfig.contactEndpoint?'ODESLAT NEZÁVAZNOU POPTÁVKU':'PŘIPRAVIT NEZÁVAZNOU POPTÁVKU'} <span>↗</span></button>}</form></DialogContent></Dialog>
}
